name: ci 
on:
  release:
    tags:
      - 'v*.*.*'
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install docs dependencies
        run: pip install -r requirements.txt 
      - name: Fetch GH-PAGES
        run: git fetch origin gh-pages --depth=1
      - name: Setup Git User
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com
      - name: Publish new doc version and set it as latest
        run:  mike alias -b gh-pages --update-aliases ${{ github.event.release.tag_name }} latest --push
      - name: Change default latest version
        run:  mike set-default latest --push

